// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi73IXFjKqVTh2o8PZ6t8oPOP9S8aam2M',
    appId: '1:910835817206:web:db7f7d6c651b877a5b2ad7',
    messagingSenderId: '910835817206',
    projectId: 'flutter-ecommerce-6f218',
    authDomain: 'flutter-ecommerce-6f218.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-6f218.firebasestorage.app',
    measurementId: 'G-8C1G6J6XY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd9oDgy3CiNd6L8R-Q6qfZVVQO7gWREgM',
    appId: '1:910835817206:android:92e09cfdfb6305cd5b2ad7',
    messagingSenderId: '910835817206',
    projectId: 'flutter-ecommerce-6f218',
    storageBucket: 'flutter-ecommerce-6f218.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqTb8OSZaipvJhrHD2RiR6IYs1mZUVHa8',
    appId: '1:910835817206:ios:ea0418e0519a90db5b2ad7',
    messagingSenderId: '910835817206',
    projectId: 'flutter-ecommerce-6f218',
    storageBucket: 'flutter-ecommerce-6f218.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqTb8OSZaipvJhrHD2RiR6IYs1mZUVHa8',
    appId: '1:910835817206:ios:ea0418e0519a90db5b2ad7',
    messagingSenderId: '910835817206',
    projectId: 'flutter-ecommerce-6f218',
    storageBucket: 'flutter-ecommerce-6f218.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi73IXFjKqVTh2o8PZ6t8oPOP9S8aam2M',
    appId: '1:910835817206:web:66a67b02c3b33a575b2ad7',
    messagingSenderId: '910835817206',
    projectId: 'flutter-ecommerce-6f218',
    authDomain: 'flutter-ecommerce-6f218.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-6f218.firebasestorage.app',
    measurementId: 'G-65R00JVQ5S',
  );
}
